version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /home/terike/wakeonlan-webapp-root/proxy/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped